-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaImages/db/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ai_images (
  ai_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ai_image_title BLOB NOT NULL, ai_status SMALLINT UNSIGNED DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX ai_id ON /*_*/ai_images (ai_id);

CREATE UNIQUE INDEX ai_image_title ON /*_*/ai_images (ai_image_title);
