-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaImages/db/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ai_images (
  ai_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  ai_image_title VARBINARY(255) NOT NULL,
  ai_status TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  UNIQUE INDEX ai_id (ai_id),
  UNIQUE INDEX ai_image_title (ai_image_title),
  PRIMARY KEY(ai_id)
) /*$wgDBTableOptions*/;
