-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaImages/db/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ai_images (
  ai_id SERIAL NOT NULL,
  ai_image_title TEXT NOT NULL,
  ai_status SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(ai_id)
);

CREATE UNIQUE INDEX ai_id ON ai_images (ai_id);

CREATE UNIQUE INDEX ai_image_title ON ai_images (ai_image_title);
